### ISSUE TITLE
Elasticsearch 1.2

### ISSUE THREAD

**Issue by maxmetagravity** [reachkrishnaraj/kafka-elasticsearch-standalone-consumer#1]
Can it support up to elasticsearch 1.2 ？

**Comment by phani546** [comment]
Hi
  will kafka support es 1.4.2 version? i installed plugin for es 1.4.2 version all setup has been done but when i starting kafka i am getting following exception please suggest me how it will work?

  Exception happened when trying to Initialize ConsumerJob object
******* NOT able to start Consumer Daemon *******

Thanks
phani
