### ISSUE TITLE
Why not use a river?

### ISSUE THREAD

**Issue by ertug** [reachkrishnaraj/kafka-elasticsearch-standalone-consumer#2]
Hi,

There is also a river for Kafka [1]. What is the advantage of using a standalone consumer?
I think adding such a comparison to README would clarify use cases.

Thank you,
Ertug

[1] https://github.com/endgameinc/elasticsearch-river-kafka

**Comment by utmishra** [comment]
https://www.elastic.co/blog/deprecating-rivers
