### ISSUE TITLE
Failed to post messages to ElasticSearch: None of the configured nodes are available: []

### ISSUE THREAD

**Issue by 3quanfeng** [reachkrishnaraj/kafka-elasticsearch-standalone-consumer#23]
Hello guys, thanks for the tool you guys created, it's really awesome.
I just downloaded it yesterday and started to play with it....
I got some issue when I run this tool to read event(json) from broker and write them to ES.
I set up all the things in the same box(an ec2 instance) including kafka(2.10.0-0.8.2.1), kafka-elasticsearch-standalone-consumer(branch 2.0) and Elasticsearch(2.1.1)

Create a "test" topic, only 1 partition
bin/kafka-topics.sh --create --zookeeper localhost:2181 --replication-factor 1 --partitions 1 --topic test

Send message:

[ec2-user@xxxx kafka_2.10-0.8.2.1]$ bin/kafka-console-producer.sh --broker-list localhost:9092 --topic test
[2016-01-12 23:46:44,492] WARN Property topic is not valid (kafka.utils.VerifiableProperties)
{"index":{"_id":"6"}}
{"account_number":6,"balance":5686,"firstname":"Hattie","lastname":"Bond","age":36,"gender":"M","address":"671 Bristol Street","employer":"Netagy","email":"
hattiebond@netagy.com","city":"Dante","state":"TN"}

And then run kafka-elasticsearch-standalone-consumer(config is provided below)
HERE IS THE LOG:
23:56:43,607 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [/home/ec2-user/apps/kafka/logback.xml] at [file:/home/ec2-user/apps/kafka/logback.xml]
23:56:43,708 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
23:56:43,729 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
23:56:43,734 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
23:56:43,863 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - This appender no longer admits a layout as a sub-component, set an encoder instead.
23:56:43,863 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - To ensure compatibility, wrapping your layout in LayoutWrappingEncoder.
23:56:43,863 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - See also http://logback.qos.ch/codes.html#layoutInsteadOfEncoder for details
23:56:43,863 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
23:56:43,867 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [MAIN_LOGS]
23:56:43,914 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - Will use gz compression
23:56:43,915 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - Will use the pattern /tmp/kafka_es_indexer-%d{yyyy-MM-dd}.%i.log for the active file
23:56:43,918 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@63e2203c - The date pattern is 'yyyy-MM-dd' from file name pattern '/tmp/kafka_es_indexer-%d{yyyy-MM-dd}.%i.log.gz'.
23:56:43,919 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@63e2203c - Roll-over at midnight.
23:56:43,923 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@63e2203c - Setting initial period to Tue Jan 12 23:56:25 UTC 2016
23:56:43,930 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
23:56:43,945 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[MAIN_LOGS] - Active log file name: /tmp/kafka_es_indexer.log
23:56:43,945 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[MAIN_LOGS] - File property is set to [/tmp/kafka_es_indexer.log]
23:56:43,946 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
23:56:43,946 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FAILED_EVENTS]
23:56:43,949 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - No compression will be used
23:56:43,949 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - Will use the pattern /tmp/failed_es_events-%d{yyyy-MM-dd}.%i.log for the active file
23:56:43,951 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@1efed156 - The date pattern is 'yyyy-MM-dd' from file name pattern '/tmp/failed_es_events-%d{yyyy-MM-dd}.%i.log'.
23:56:43,951 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@1efed156 - Roll-over at midnight.
23:56:43,951 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@1efed156 - Setting initial period to Tue Jan 12 22:19:15 UTC 2016
23:56:43,956 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
23:56:43,957 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FAILED_EVENTS] - Active log file name: /tmp/failed_es_events.log
23:56:43,957 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FAILED_EVENTS] - File property is set to [/tmp/failed_es_events.log]
23:56:43,958 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.elasticsearch.kafka.indexer.FailedEventsLogger] to ERROR
23:56:43,958 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FAILED_EVENTS] to Logger[org.elasticsearch.kafka.indexer.FailedEventsLogger]
23:56:43,959 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.elasticsearch.kafka] to INFO
23:56:43,959 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [MAIN_LOGS] to Logger[org.elasticsearch.kafka]
23:56:44,334 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[org.elasticsearch.kafka]
23:56:44,334 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
23:56:44,336 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@6737fd8f - Registering current configuration as safe fallback point

12/Jan/2016:23:56:44:343 +0000 [main] INFO  o.e.kafka.indexer.KafkaIndexerDriver - Initializing Kafka ES Indexer, arguments passed to the Driver: 
12/Jan/2016:23:56:44:346 +0000 [main] INFO  o.e.kafka.indexer.KafkaIndexerDriver - /home/ec2-user/apps/kafka/kafka-es-indexer.properties
12/Jan/2016:23:56:44:347 +0000 [main] INFO  o.e.kafka.indexer.ConsumerConfig - configFile : /home/ec2-user/apps/kafka/kafka-es-indexer.properties
12/Jan/2016:23:56:44:348 +0000 [main] INFO  o.e.kafka.indexer.ConsumerConfig - Properties : {esIndexingRetrySleepTimeMs=10000, kafkaZookeeperList=localhost:2181, appStopTimeoutSeconds=10, esIndex=kafkaESIndex, startOffsetFrom=RESTART, esClusterName=sca, kafkaFetchSizeMinBytes=31457280, zkConnectionTimeoutMs=15000, messageEncoding=UTF-8, indexHandlerClass=org.elasticsearch.kafka.indexer.BasicIndexHandler, kafkaBrokersList=localhost:9092, kafkaSimpleConsumerBufferSizeBytes=31457280, zkCuratorRetryDelayMs=2000, consumerSleepBetweenFetchsMs=10, kafkaReinitSleepTimeMs=10000, isPerfReportingEnabled=false, esHostPortList=localhost:9300, topic=test, messageHandlerClass=org.elasticsearch.kafka.indexer.messageHandlers.RawMessageStringHandler, lastPartition=0, kafkaSimpleConsumerSocketTimeoutMs=10000, numberOfReinitTries=2, consumerGroupName=kafka_es_indexer, startOffset=0, firstPartition=0, numberOfEsIndexingRetryAttempts=2, zkCuratorRetryTimes=3, zkSessionTimeoutMs=10000, isDryRun=false, esIndexType=kafkaESType}
12/Jan/2016:23:56:44:349 +0000 [main] INFO  o.e.kafka.indexer.ConsumerConfig - Config reading complete !
12/Jan/2016:23:56:44:349 +0000 [main] INFO  o.e.kafka.indexer.KafkaIndexerDriver - Created kafka consumer config OK
12/Jan/2016:23:56:44:350 +0000 [main] INFO  o.e.k.indexer.jobs.IndexerJobManager - ConsumerJobManager is starting, servicing partitions: [0-0]
12/Jan/2016:23:56:44:351 +0000 [main] INFO  o.e.kafka.indexer.KafkaIndexerDriver - Registering KafkfaEsIndexerStatus MBean: 
12/Jan/2016:23:56:44:445 +0000 [main] INFO  o.e.k.indexer.jobs.IndexerJobManager - Creating IndexerJob for partition=0
12/Jan/2016:23:56:44:450 +0000 [main] INFO  o.e.kafka.indexer.jobs.IndexerJob - Initializing ElasticSearch... hostPortList=localhost:9300, esClusterName=sca for partition 0
log4j:WARN No appenders could be found for logger (org.elasticsearch.plugins).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
12/Jan/2016:23:56:45:294 +0000 [main] INFO  o.e.kafka.indexer.jobs.IndexerJob - adding [localhost:9300] to TransportClient for partition 0... 
12/Jan/2016:23:56:45:474 +0000 [main] INFO  o.e.kafka.indexer.jobs.IndexerJob - ElasticSearch Client created and intialized OK for partition 0
12/Jan/2016:23:56:45:474 +0000 [main] INFO  o.e.kafka.indexer.jobs.IndexerJob - Initializing Kafka for partition 0...
12/Jan/2016:23:56:45:474 +0000 [main] INFO  o.e.kafka.indexer.jobs.IndexerJob - kafkaClientId=kafka_es_indexer_0 for partition 0
12/Jan/2016:23:56:45:476 +0000 [main] INFO  o.e.kafka.indexer.KafkaClient - Instantiating KafkaClient
12/Jan/2016:23:56:45:476 +0000 [main] INFO  o.e.kafka.indexer.KafkaClient - ### KafkaClient Config: ###
12/Jan/2016:23:56:45:476 +0000 [main] INFO  o.e.kafka.indexer.KafkaClient - kafkaZookeeperList: localhost:2181
12/Jan/2016:23:56:45:476 +0000 [main] INFO  o.e.kafka.indexer.KafkaClient - kafkaBrokersList: localhost:9092
12/Jan/2016:23:56:45:477 +0000 [main] INFO  o.e.kafka.indexer.KafkaClient - kafkaClientId: kafka_es_indexer_0
12/Jan/2016:23:56:45:477 +0000 [main] INFO  o.e.kafka.indexer.KafkaClient - topic: test
12/Jan/2016:23:56:45:477 +0000 [main] INFO  o.e.kafka.indexer.KafkaClient - partition: 0
12/Jan/2016:23:56:45:515 +0000 [main] INFO  o.e.kafka.indexer.KafkaClient - Connected to Kafka Zookeeper successfully
12/Jan/2016:23:56:45:515 +0000 [main] INFO  o.e.kafka.indexer.KafkaClient - Looking for Kafka leader broker for partition 0...
12/Jan/2016:23:56:45:515 +0000 [main] INFO  o.e.kafka.indexer.KafkaClient - Looking for leader for partition 0 using Kafka Broker=localhost:9092, topic=test
12/Jan/2016:23:56:45:985 +0000 [main] INFO  o.e.kafka.indexer.KafkaClient - Found leader for partition 0 using Kafka Broker=localhost:9092, topic=test; leader broker URL: 0.0.0.0:9092
12/Jan/2016:23:56:45:987 +0000 [main] INFO  o.e.kafka.indexer.KafkaClient - Found leader: leaderBrokerURL=0.0.0.0:9092
12/Jan/2016:23:56:45:990 +0000 [main] INFO  o.e.kafka.indexer.KafkaClient - Initialized Kafka Consumer successfully for partition 0
12/Jan/2016:23:56:45:990 +0000 [main] INFO  o.e.kafka.indexer.jobs.IndexerJob - Kafka client created and intialized OK for partition 0
12/Jan/2016:23:56:45:990 +0000 [main] INFO  o.e.kafka.indexer.jobs.IndexerJob - MessageHandler Class given in config is org.elasticsearch.kafka.indexer.messageHandlers.RawMessageStringHandler for partition 0
12/Jan/2016:23:56:45:993 +0000 [main] INFO  o.e.kafka.indexer.MessageHandler - Created IndexHandler: 
12/Jan/2016:23:56:45:994 +0000 [main] INFO  o.e.kafka.indexer.MessageHandler - Created Message Handler
12/Jan/2016:23:56:45:994 +0000 [main] INFO  o.e.k.i.m.RawMessageStringHandler - Initialized RawMessageStringHandler
12/Jan/2016:23:56:45:995 +0000 [kafka-indexer-consumer-thread-0] INFO  o.e.kafka.indexer.jobs.IndexerJob - ******\* Starting a new batch of events from Kafka for partition 0 ...
12/Jan/2016:23:56:45:995 +0000 [kafka-indexer-consumer-thread-0] INFO  o.e.kafka.indexer.jobs.IndexerJob - ***\* Computing Kafka offset **\* for partition 0
12/Jan/2016:23:56:45:996 +0000 [kafka-indexer-consumer-thread-0] INFO  o.e.kafka.indexer.jobs.IndexerJob - startOffsetFrom=RESTART for partition 0
12/Jan/2016:23:56:45:996 +0000 [kafka-indexer-consumer-thread-0] INFO  o.e.kafka.indexer.jobs.IndexerJob - Restarting from where the Offset is left for topic test, for partition 0
12/Jan/2016:23:56:46:012 +0000 [kafka-indexer-consumer-thread-0] INFO  o.e.kafka.indexer.jobs.IndexerJob - offsetForThisRound is set to the CurrentOffset: 0 for partition 0
12/Jan/2016:23:56:46:038 +0000 [kafka-indexer-consumer-thread-0] INFO  o.e.kafka.indexer.jobs.IndexerJob - Resulting offsetForThisRound = 0 for partition 0
12/Jan/2016:23:56:46:071 +0000 [kafka-indexer-consumer-thread-0] INFO  o.e.kafka.indexer.MessageHandler - Total # of messages in this batch: 6; # of successfully transformed and added to Index messages: 6; offsetOfNextBatch: 6
12/Jan/2016:23:56:46:071 +0000 [kafka-indexer-consumer-thread-0] INFO  o.e.kafka.indexer.jobs.IndexerJob - posting the messages to ElasticSearch for partition 0...
12/Jan/2016:23:56:46:077 +0000 [kafka-indexer-consumer-thread-0] ERROR o.e.kafka.indexer.MessageHandler - Failed to post messages to ElasticSearch: None of the configured nodes are available: []
org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: []

MY CONFIG:
kafkaZookeeperList=localhost:2181
zkSessionTimeoutMs=10000
zkConnectionTimeoutMs=15000
zkCuratorRetryTimes=3
zkCuratorRetryDelayMs=2000
kafkaBrokersList=localhost:9092
consumerGroupName=kafka_es_indexer
topic=test
firstPartition=0
lastPartition=0
startOffsetFrom=RESTART
startOffset=0
kafkaFetchSizeMinBytes=31457280
kafkaSimpleConsumerBufferSizeBytes=31457280
kafkaSimpleConsumerSocketTimeoutMs=10000
appStopTimeoutSeconds=10
numberOfReinitTries=2
kafkaReinitSleepTimeMs=10000
esHostPortList=localhost:9300
esClusterName=sca
esIndex=kafkaESIndex
esIndexType=kafkaESType
messageHandlerClass=org.elasticsearch.kafka.indexer.messageHandlers.RawMessageStringHandler
indexHandlerClass=org.elasticsearch.kafka.indexer.BasicIndexHandler
messageEncoding=UTF-8
isDryRun=false
consumerSleepBetweenFetchsMs=10
numberOfEsIndexingRetryAttempts=2
esIndexingRetrySleepTimeMs=10000
isPerfReportingEnabled=false

TROUBLESHOOTING:

I acutually verified that I can run ElasticSearch API manually to do the bulk post with different index and it just works perfectly:

curl -XPOST 'localhost:9200/customer/external/_bulk?pretty' -d '
{"index":{"_id":"1"}}
{"name": "John Doe" }
{"index":{"_id":"2"}}
{"name": "Jane Doe" }
'

Here is the code I can find where throw the exception:

public boolean postToElasticSearch() throws Exception {
        BulkResponse bulkResponse = null;
        BulkItemResponse bulkItemResp = null;
        //Nothing/NoMessages to post to ElasticSearch
        if(bulkRequestBuilder.numberOfActions() <= 0){
            logger.warn("No messages to post to ElasticSearch - returning");
            return true;
        }  
        try{
            bulkResponse = bulkRequestBuilder.execute().actionGet();
        }
        catch(ElasticsearchException e){
            logger.error("Failed to post messages to ElasticSearch: " + e.getMessage(), e);
            throw e;
        }
                ....

the elasticsearch port is 9300 which is used in the config...
I tried 9200 as well, and it didn't work either....

Please help look into the issue, I don't think it would be a connection issue to elasticsearch since they are in the same box.

Thanks in advance!

**Comment by reachkrishnaraj** [comment]
Hi @3quanfeng : Pls dont use "esHostPortList=localhost:9300". Pls provide a IP address or Full Host Name. I have come across this issue during my development. Its good practice to provide the same(P address or Full Host Name) for Kafka too.

I mean, like esHostPortList=<127.xx.xx.xxx>:9300

**Comment by 3quanfeng** [comment]
Thanks, I will definitely try that...
btw..does the version(branch 2.0) support elasticsearch 2.1.x

**Comment by 3quanfeng** [comment]
Hi @reachkrishnaraj , I just tried what you suggested, still got the same problem "Failed to post messages to ElasticSearch: None of the configured nodes are available: []"

kafkaZookeeperList=10.2.x.x:2181
kafkaBrokersList=10.2.x.x:9092
esHostPortList=10.2.x.x:9300

I also restart kafka server as well as ElasticSearch to make it use the same IP address as above

the IP address(10.2.x.x) above is inet address of eth0

The java env I am using is:
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)
[ec2-user@XXXX]$ echo $JAVA_HOME
/usr/java/latest

from the elasticsearch log at the same time, I can find:

[2016-01-13 01:45:58,396][WARN ][transport.netty          ] [Falcon] exception caught on transport layer [[id: 0x0a5723c1, /10.2.x.x:39889 => /10.2.x.x:9300]], closing connection
java.lang.IllegalStateException: Message not fully read (request) for requestId [4], action [cluster/nodes/info], readerIndex [39] vs expected [57]; resetting
at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:120)
at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
    at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
    at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
    at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
    at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
    at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
    at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
    at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:75)
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
    at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
    at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
    at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
    at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
    at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

Thanks in advance!

**Comment by ppine7** [comment]
Hi @3quanfeng!
A few avenues to try:
-- can you try to setup the whole thing on your local server/laptop (either Mac or *nix ) - to eliminate the possible issues with communication on AWS EC2 (security groups config, IPs, etc.)
-- if not - try to open 9300 port to everybody on your EC2 , and also use private vs. public EC2 IPs
-- ES2.x is not supported/tested yet. And while I don't see why it should not work - could you try to use ES 1.x instead?

We are thinking of upgrading to ES2.x and Kafka0.9.x in the near future - but it is not yet planned/discussed.

Thanks for trying the project!
Marina

**Comment by 3quanfeng** [comment]
Thanks @ppine7 
the IP(10.2.x.x.) I used above is actually private IP address and since everything is in the same EC2 box, the securitygroup should not be an issue...

A good thing is that I tried with different lower verison of ES(1.x), the tool works with ES 1.4.2 to some extent but It doesn't work when use ES 1.7.4(got the same issue as I submitted)

when tested it with ES 1.4.2, there are some issues when I did search with elasticsearch

The event I send through producer(2.10.0-0.9.0) is:
[ec2-user@xxxxxx]$ bin/kafka-console-producer.sh --broker-list localhost:9092 --topic test
{"index":{"_id":"894"}}
{"account_number":894,"balance":1031,"firstname":"Tyler","lastname":"Fitzgerald","age":32,"gender":"M","address":"787 Meserole Street","employer":"Jetsilk","email":"tylerfitzgerald@jetsilk.com","city":"Woodlands","state":"WV"}

While when I did search, the "_id" returned is just not right:
curl '10.2.x.x:9200/testindex/_search?q=*&pretty'
{
  "took" : 36,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 2,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : "testindex",
      "_type" : "testtype",
      "_id" : "AVI5pcP9UHpfGAa-2ito",   --- should be 894 ---
      "_score" : 1.0,
      "_source":{"account_number":894,"balance":1031,"firstname":"Tyler","lastname":"Fitzgerald","age":32,"gender":"M","address":"787 Meserole Street","employer":"Jetsilk","email":"tylerfitzgerald@jetsilk.com","city":"Woodlands","state":"WV"}
    }, {
      "_index" : "testindex",
      "_type" : "testtype",
      "_id" : "AVI5pZx3UHpfGAa-2itn",
      "_score" : 1.0,
      "_source":{"index":{"_id":"894"}}
    } ]
  }
}

**Comment by ppine7** [comment]
Ah, Ok, now it makes sense :)
So, the default index manager that you are using out of the box does not use any fields as Dcoument IDs for ES. It relies on autogenerated IDs by ES. 
The actual fix is very easy - all that is needed as adding the ID as part of the bulk request creation, in the MessageHandler's prepareForPostToElasticSearch() method. The code to add ID (called eventUUID below), if it is know, would like like this:

this.getBuildReqBuilder().add(
    esClient.prepareIndex(
        indexHandler.getIndexName(null), indexHandler.getIndexType(null), eventUUID)
    .setSource(transformedMessage)

However, making this change is a bit convoluted now as it is not exposed as something you can over-write in your custom MessageHandler implementation - as you should.... We will definitely look into adding this capability, as it is a very reasonable desire to use "_id" (or any other field) as a document ID, if it is present.

For now, my suggestion is that you create your own custom implementation of the  MessageHandler (you can extend the top level MessageHandler) - and not only provide your implementation of the transformMessage() method - bur also overwrite the prepareForPostToElasticSearch() and add parsing of the message, figuring out value of the "_id" and adding it to the request builder as I specified above.

Now, regarding the ES2.x and ES1.7.x:
Currently we use ES1.5.1 - and it works great.
I'm surprised 1.7 did not work - but not surprised too much about 2.x, as APIs have changed in 2.x and ESClient is created differently.
This is certainly something we will consider adding soon, as most people start using ES2.x now.

thanks,
Marina

**Comment by 3quanfeng** [comment]
Thanks @ppine7, it would be great have it support the latest ES and Kafka Consumer!
Thanks again for the project
