### ISSUE TITLE
Class KafkaIndexerDriver compile error

### ISSUE THREAD

**Issue by wjw178** [reachkrishnaraj/kafka-elasticsearch-standalone-consumer#26]
The KafkaIndexerDriver driver should be declared with final in main method

Cannot refer to the non-final local variable driver defined in an enclosing scope

**Comment by ppine7** [comment]
Hi, wjw178,
What is the error you are getting and how do you compile the project?
There is no need for "final" main - there are no references to final variables. If you follow the documentation - and compile/build the project via "mvn clean package" - you should not have any issues.

Please make sure you use the latest 'branch2.0'

thanks,
Marina

**Comment by wjw178** [comment]
In the method main of Class KafkaIndexerDriver：
A shutdown hook thread  reference the non final filed "driver" raise compile error, need specify by final?

**Comment by ppine7** [comment]
'driver' is a local non-final variable in the main() method...
Did you actually try to compile/build the project or are you just looking at the code?
If you do get a compile error - please post the full stack trace here, along with the command you use to build/compile.

**Comment by wjw178** [comment]
Hi, Marina
   Thank you for your reply. Here now midnight so just sorry to cannot give a clear stack trace here.
    In fact i clone the branch 2.0, and modify the code to update the Elastic java api to 2.x.  And now
i deployed the project  In  my  test  ENV And running well. Thanks a lot for your code. 
    This issue  i just  describe is when i clone code first time and  run command " mvn package  " , console  stack show  compile error.  Then i importe the code  to eclipse ,also IDE tips This non-final issue.  And i both try JDK 1.7.x(updated) version And 1.8.x .
  In my mind,  it is a syntax issue, but seems u have no issue like me ?  Or m i make a stupid joke? ^_^

**Comment by ppine7** [comment]
Strange - I do not have any issues with the non-final 'driver' field - 'mvn clean package' works like a charm and creates a working kafka-es-indexer.2.0.jar ....
Please do post your full stack trace - I'm very curios why this is happening in your case.

Awesome, glad to hear you made it work for ES2.0 - we are also planing to add support to ES2.0, different branch, probably, as it won't be compatible with older ES.
You are welcome to contribute as well, of course :) !

thanks,
Marina

**Comment by reachkrishnaraj** [comment]
Closed the ticket.
